config/routes.rb
Rails.application.routes.draw do
  resources :pins
  devise_for :users
  root 'home#index'
  get 'home/about'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pin.rb
class Pin < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end

  def about
  end
end

app/controllers/pins_controller.rb
class PinsController < ApplicationController
  before_action :set_pin, only: %i[ show edit update destroy ]

  # GET /pins or /pins.json
  def index
    @pins = Pin.all
  end

  # GET /pins/1 or /pins/1.json
  def show
  end

  # GET /pins/new
  def new
    @pin = Pin.new
  end

  # GET /pins/1/edit
  def edit
  end

  # POST /pins or /pins.json
  def create
    @pin = Pin.new(pin_params)

    respond_to do |format|
      if @pin.save
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully created." }
        format.json { render :show, status: :created, location: @pin }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pins/1 or /pins/1.json
  def update
    respond_to do |format|
      if @pin.update(pin_params)
        format.html { redirect_to pin_url(@pin), notice: "Pin was successfully updated." }
        format.json { render :show, status: :ok, location: @pin }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pin.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pins/1 or /pins/1.json
  def destroy
    @pin.destroy!

    respond_to do |format|
      format.html { redirect_to pins_url, notice: "Pin was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pin
      @pin = Pin.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pin_params
      params.require(:pin).permit(:description)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/pins_helper.rb
module PinsHelper
end

app/views/home/_header.html.erb
<nav class="navbar navbar-expand-lg bg-light">
  <div class="container">
    <a class="navbar-brand" href="#">Pinterest3d</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <%= link_to 'Home', root_path, class: 'nav-link active' %>
        </li>
        <li class="nav-item">
          <%= link_to "About Us", home_about_path, class: 'nav-link' %>
        </li>
        <li class="nav-item">
          <%= link_to "Pins", pins_path, class: 'nav-link' %>
        </li>
        <!-- User login, logout and registration -->
        <% if user_signed_in? %>
          <li class="nav-item"><%= link_to 'Edit Profile', edit_user_registration_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Logout', destroy_user_session_path, method: :delete, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Add Pin', new_pin_path, class: 'nav-link' %></li>
        <% else %>
          <li class="nav-item"><%= link_to 'Login', new_user_session_path, class: 'nav-link' %></li>
          <li class="nav-item"><%= link_to 'Register', new_user_registration_path, class: 'nav-link' %></li>
        <% end %>
      </ul>
      <form class="d-flex" role="search">
        <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
        <button class="btn btn-outline-success" type="submit">Search</button>
      </form>
    </div>
  </div>
</nav>

app/views/home/about.html.erb
<h1>About Me...</h1>

<p>It doesn't matter, but I'm building a Pinterest clone!</p>

app/views/home/index.html.erb
<h1>Welcome to my app</h1>
<p>It's a work in progress!</p>

<%= link_to'About Us', home_about_path, class: 'btn btn-light' %>

<%= link_to 'Home', root_path, class: 'btn btn-primary' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Pinterested</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-QWTKZyjpPEjISv5WaRU9OFeRpok6YctnYmDr5pNlyT2bRjXh0JMhjY6hW+ALEwIH" crossorigin="anonymous">

    <meta name="viewport" content="width=device-width, initial-scale=1">
  </head>

  <body>
    <%= render 'home/header' %>

    <div class="container mt-5">

      <p class="notice"><%= notice %></p> <!-- Might need to change this, check pg. 145 of the book -->
      <p class="alert"><%= alert %></p>

      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-YvpcrYf0tY3lHB60NNkmXc5s9fDVZLESaAA55NDzOxhy9GkcIdslK1eN7N6jIeHz" crossorigin="anonymous"></script>
  </body>
</html>

app/views/pins/_form.html.erb
<div class="row">
  <div class="card" style="width: 500px;">
    <div class="card-body">
      <%= form_with(model: pin) do |form| %>
        <% if pin.errors.any? %>
          <div style="color: red">
            <h2><%= pluralize(pin.errors.count, "error") %> prohibited this pin from being saved:</h2>

            <ul>
              <% pin.errors.each do |error| %>
                <li><%= error.full_message %></li>
              <% end %>
            </ul>
          </div>
        <% end %>

        <div>
          <%= form.label :description, style: "display: block" %>
          <%= form.text_field :description %>
        </div>

        <div class="mt-3">
          <%= form.submit %>
        </div>
      <% end %>
    </div>
  </div>
</div>

app/views/pins/_pin.html.erb
<div id="<%= dom_id pin %>">
  <p>
    <strong>Description:</strong>
    <%= pin.description %>
  </p>

</div>

app/views/pins/edit.html.erb
<h1>Editing pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Show this pin", @pin %> |
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/index.html.erb
<p style="color: green"><%= notice %></p>

<h1>Pins</h1>

<div id="pins">
  <% @pins.each do |pin| %>
    <%= render pin %>
    <p>
      <%= link_to "Show this pin", pin %>
    </p>
  <% end %>
</div>

<%= link_to "New pin", new_pin_path %>

app/views/pins/new.html.erb
<h1>New pin</h1>

<%= render "form", pin: @pin %>

<br>

<div>
  <%= link_to "Back to pins", pins_path %>
</div>

app/views/pins/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pin %>

<div>
  <%= link_to "Edit this pin", edit_pin_path(@pin) %> |
  <%= link_to "Back to pins", pins_path %>

  <%= button_to "Destroy this pin", @pin, method: :delete %>
</div>